import pathlib

### SERVER INFORMATION
DEFAULT_PORT = 64209
DEFAULT_ADDRESS = "0.0.0.0"
LOGIN_INFO_FILE = str(pathlib.Path().absolute()) + '/usrdata'

### Package information
ENCODING = 'utf8'
SEPARATOR = '|'

### Protocols
PROTOCOL_LOGIN = 1
PROTOCOL_SHUTDOWN = 2
PROTOCOL_UNKNOWN = 3
PROTOCOL_SERVER_CLOSING = 4
PROTOCOL_MSG = 5
PROTOCOL_LOGIN_DENY = 6
PROTOCOL_LOGIN_ACCEPT = 7
PROTOCOL_JOIN_ROOM = 8
PROTOCOL_LEAVE_ROOM = 9
PROTOCOL_LIST_ROOMS = 10
PROTOCOL_PRIVATE_MSG = 11
PROTOCOL_LIST_USERS = 12
PROTOCOL_USER_NOT_FOUND = 13
PROTOCOL_KICK_USER = 14
PROTOCOL_DELETE_ROOM = 15
PROTOCOL_ROOM_NOT_FOUND = 16

